/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommodityImpact {
  'direction' : { 'up' : null } |
    { 'down' : null } |
    { 'neutral' : null },
  'commodity' : string,
  'magnitude' : number,
}
export interface CorrelationChain {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'steps' : Array<CorrelationStep>,
}
export interface CorrelationStep {
  'eventId' : string,
  'description' : string,
  'stepLabel' : string,
}
export interface CountryRiskProfile {
  'country' : string,
  'socialUnrest' : number,
  'politicalStability' : number,
  'lastUpdated' : Time,
  'militaryActivity' : number,
  'countryCode' : string,
  'sanctionsRisk' : number,
  'overallRisk' : number,
  'tradeDependency' : number,
  'economicScore' : number,
}
export interface EventCorrelation {
  'id' : string,
  'targetEventId' : string,
  'sourceEventId' : string,
  'description' : string,
  'strength' : number,
  'relationshipType' : string,
}
export interface GlobalEvent {
  'id' : string,
  'lat' : number,
  'lng' : number,
  'region' : string,
  'title' : string,
  'country' : string,
  'tags' : Array<string>,
  'description' : string,
  'timestamp' : Time,
  'category' : { 'climate' : null } |
    { 'trade' : null } |
    { 'geopolitics' : null } |
    { 'military' : null } |
    { 'technology' : null } |
    { 'economic' : null } |
    { 'policy' : null },
  'severity' : bigint,
}
export interface IndustryImpact {
  'direction' : { 'up' : null } |
    { 'down' : null } |
    { 'neutral' : null },
  'magnitude' : number,
  'industry' : string,
  'reason' : string,
}
export interface InfluenceEdge {
  'id' : string,
  'relationship' : string,
  'description' : string,
  'strength' : number,
  'entityType' : { 'country' : null } |
    { 'institution' : null } |
    { 'corporation' : null },
  'targetEntity' : string,
  'sourceEntity' : string,
}
export interface MarketImpact {
  'id' : string,
  'eventId' : string,
  'industryImpacts' : Array<IndustryImpact>,
  'createdAt' : Time,
  'eventTitle' : string,
  'commodityImpacts' : Array<CommodityImpact>,
}
export interface PolicyEntry {
  'id' : string,
  'title' : string,
  'country' : string,
  'policyType' : policyType,
  'marketImpact' : string,
  'description' : string,
  'severity' : bigint,
  'effectiveDate' : Time,
}
export interface Scenario {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'outcomes' : Array<ScenarioOutcome>,
  'triggerEventId' : string,
}
export interface ScenarioOutcome {
  'probability' : number,
  'title' : string,
  'timelineWeeks' : bigint,
  'description' : string,
  'sectorsImpacted' : Array<string>,
}
export interface SentimentRecord {
  'id' : string,
  'region' : string,
  'country' : string,
  'sentimentScore' : number,
  'source' : string,
  'recordedAt' : Time,
  'narrativeTheme' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'organization' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type policyType = { 'regulation' : null } |
  { 'tariff' : null } |
  { 'environmental' : null } |
  { 'sanction' : null } |
  { 'export' : null } |
  { 'monetary' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGlobalEvent' : ActorMethod<[GlobalEvent], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createScenario' : ActorMethod<[Scenario], undefined>,
  'getAllCorrelationChains' : ActorMethod<[], Array<CorrelationChain>>,
  'getAllCountryRiskProfiles' : ActorMethod<[], Array<CountryRiskProfile>>,
  'getAllGlobalEvents' : ActorMethod<
    [
      [] | [
        { 'climate' : null } |
          { 'trade' : null } |
          { 'geopolitics' : null } |
          { 'military' : null } |
          { 'technology' : null } |
          { 'economic' : null } |
          { 'policy' : null }
      ],
    ],
    Array<GlobalEvent>
  >,
  'getAllInfluenceEdges' : ActorMethod<[], Array<InfluenceEdge>>,
  'getAllPolicyEntries' : ActorMethod<[[] | [policyType]], Array<PolicyEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCorrelationsForEvent' : ActorMethod<[string], Array<EventCorrelation>>,
  'getCountryRiskByCode' : ActorMethod<[string], CountryRiskProfile>,
  'getDashboardSummary' : ActorMethod<
    [],
    {
      'totalEvents' : bigint,
      'highRiskCountries' : Array<CountryRiskProfile>,
      'activeScenarios' : bigint,
      'avgGlobalRisk' : number,
    }
  >,
  'getEventById' : ActorMethod<[string], GlobalEvent>,
  'getMarketImpacts' : ActorMethod<[[] | [string]], Array<MarketImpact>>,
  'getScenarioById' : ActorMethod<[string], Scenario>,
  'getScenarios' : ActorMethod<[[] | [string]], Array<Scenario>>,
  'getSentimentRecords' : ActorMethod<[[] | [string]], Array<SentimentRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCountryRisk' : ActorMethod<[CountryRiskProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];