/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const GlobalEvent = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'region' : IDL.Text,
  'title' : IDL.Text,
  'country' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Variant({
    'climate' : IDL.Null,
    'trade' : IDL.Null,
    'geopolitics' : IDL.Null,
    'military' : IDL.Null,
    'technology' : IDL.Null,
    'economic' : IDL.Null,
    'policy' : IDL.Null,
  }),
  'severity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScenarioOutcome = IDL.Record({
  'probability' : IDL.Float64,
  'title' : IDL.Text,
  'timelineWeeks' : IDL.Nat,
  'description' : IDL.Text,
  'sectorsImpacted' : IDL.Vec(IDL.Text),
});
export const Scenario = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'outcomes' : IDL.Vec(ScenarioOutcome),
  'triggerEventId' : IDL.Text,
});
export const CorrelationStep = IDL.Record({
  'eventId' : IDL.Text,
  'description' : IDL.Text,
  'stepLabel' : IDL.Text,
});
export const CorrelationChain = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'steps' : IDL.Vec(CorrelationStep),
});
export const CountryRiskProfile = IDL.Record({
  'country' : IDL.Text,
  'socialUnrest' : IDL.Float64,
  'politicalStability' : IDL.Float64,
  'lastUpdated' : Time,
  'militaryActivity' : IDL.Float64,
  'countryCode' : IDL.Text,
  'sanctionsRisk' : IDL.Float64,
  'overallRisk' : IDL.Float64,
  'tradeDependency' : IDL.Float64,
  'economicScore' : IDL.Float64,
});
export const InfluenceEdge = IDL.Record({
  'id' : IDL.Text,
  'relationship' : IDL.Text,
  'description' : IDL.Text,
  'strength' : IDL.Float64,
  'entityType' : IDL.Variant({
    'country' : IDL.Null,
    'institution' : IDL.Null,
    'corporation' : IDL.Null,
  }),
  'targetEntity' : IDL.Text,
  'sourceEntity' : IDL.Text,
});
export const policyType = IDL.Variant({
  'regulation' : IDL.Null,
  'tariff' : IDL.Null,
  'environmental' : IDL.Null,
  'sanction' : IDL.Null,
  'export' : IDL.Null,
  'monetary' : IDL.Null,
});
export const PolicyEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'country' : IDL.Text,
  'policyType' : policyType,
  'marketImpact' : IDL.Text,
  'description' : IDL.Text,
  'severity' : IDL.Nat,
  'effectiveDate' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'organization' : IDL.Text,
});
export const EventCorrelation = IDL.Record({
  'id' : IDL.Text,
  'targetEventId' : IDL.Text,
  'sourceEventId' : IDL.Text,
  'description' : IDL.Text,
  'strength' : IDL.Float64,
  'relationshipType' : IDL.Text,
});
export const IndustryImpact = IDL.Record({
  'direction' : IDL.Variant({
    'up' : IDL.Null,
    'down' : IDL.Null,
    'neutral' : IDL.Null,
  }),
  'magnitude' : IDL.Float64,
  'industry' : IDL.Text,
  'reason' : IDL.Text,
});
export const CommodityImpact = IDL.Record({
  'direction' : IDL.Variant({
    'up' : IDL.Null,
    'down' : IDL.Null,
    'neutral' : IDL.Null,
  }),
  'commodity' : IDL.Text,
  'magnitude' : IDL.Float64,
});
export const MarketImpact = IDL.Record({
  'id' : IDL.Text,
  'eventId' : IDL.Text,
  'industryImpacts' : IDL.Vec(IndustryImpact),
  'createdAt' : Time,
  'eventTitle' : IDL.Text,
  'commodityImpacts' : IDL.Vec(CommodityImpact),
});
export const SentimentRecord = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'country' : IDL.Text,
  'sentimentScore' : IDL.Float64,
  'source' : IDL.Text,
  'recordedAt' : Time,
  'narrativeTheme' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGlobalEvent' : IDL.Func([GlobalEvent], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createScenario' : IDL.Func([Scenario], [], []),
  'getAllCorrelationChains' : IDL.Func(
      [],
      [IDL.Vec(CorrelationChain)],
      ['query'],
    ),
  'getAllCountryRiskProfiles' : IDL.Func(
      [],
      [IDL.Vec(CountryRiskProfile)],
      ['query'],
    ),
  'getAllGlobalEvents' : IDL.Func(
      [
        IDL.Opt(
          IDL.Variant({
            'climate' : IDL.Null,
            'trade' : IDL.Null,
            'geopolitics' : IDL.Null,
            'military' : IDL.Null,
            'technology' : IDL.Null,
            'economic' : IDL.Null,
            'policy' : IDL.Null,
          })
        ),
      ],
      [IDL.Vec(GlobalEvent)],
      ['query'],
    ),
  'getAllInfluenceEdges' : IDL.Func([], [IDL.Vec(InfluenceEdge)], ['query']),
  'getAllPolicyEntries' : IDL.Func(
      [IDL.Opt(policyType)],
      [IDL.Vec(PolicyEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCorrelationsForEvent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EventCorrelation)],
      ['query'],
    ),
  'getCountryRiskByCode' : IDL.Func(
      [IDL.Text],
      [CountryRiskProfile],
      ['query'],
    ),
  'getDashboardSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEvents' : IDL.Nat,
          'highRiskCountries' : IDL.Vec(CountryRiskProfile),
          'activeScenarios' : IDL.Nat,
          'avgGlobalRisk' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getEventById' : IDL.Func([IDL.Text], [GlobalEvent], ['query']),
  'getMarketImpacts' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(MarketImpact)],
      ['query'],
    ),
  'getScenarioById' : IDL.Func([IDL.Text], [Scenario], ['query']),
  'getScenarios' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Scenario)],
      ['query'],
    ),
  'getSentimentRecords' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(SentimentRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCountryRisk' : IDL.Func([CountryRiskProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const GlobalEvent = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'region' : IDL.Text,
    'title' : IDL.Text,
    'country' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Variant({
      'climate' : IDL.Null,
      'trade' : IDL.Null,
      'geopolitics' : IDL.Null,
      'military' : IDL.Null,
      'technology' : IDL.Null,
      'economic' : IDL.Null,
      'policy' : IDL.Null,
    }),
    'severity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScenarioOutcome = IDL.Record({
    'probability' : IDL.Float64,
    'title' : IDL.Text,
    'timelineWeeks' : IDL.Nat,
    'description' : IDL.Text,
    'sectorsImpacted' : IDL.Vec(IDL.Text),
  });
  const Scenario = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'outcomes' : IDL.Vec(ScenarioOutcome),
    'triggerEventId' : IDL.Text,
  });
  const CorrelationStep = IDL.Record({
    'eventId' : IDL.Text,
    'description' : IDL.Text,
    'stepLabel' : IDL.Text,
  });
  const CorrelationChain = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'steps' : IDL.Vec(CorrelationStep),
  });
  const CountryRiskProfile = IDL.Record({
    'country' : IDL.Text,
    'socialUnrest' : IDL.Float64,
    'politicalStability' : IDL.Float64,
    'lastUpdated' : Time,
    'militaryActivity' : IDL.Float64,
    'countryCode' : IDL.Text,
    'sanctionsRisk' : IDL.Float64,
    'overallRisk' : IDL.Float64,
    'tradeDependency' : IDL.Float64,
    'economicScore' : IDL.Float64,
  });
  const InfluenceEdge = IDL.Record({
    'id' : IDL.Text,
    'relationship' : IDL.Text,
    'description' : IDL.Text,
    'strength' : IDL.Float64,
    'entityType' : IDL.Variant({
      'country' : IDL.Null,
      'institution' : IDL.Null,
      'corporation' : IDL.Null,
    }),
    'targetEntity' : IDL.Text,
    'sourceEntity' : IDL.Text,
  });
  const policyType = IDL.Variant({
    'regulation' : IDL.Null,
    'tariff' : IDL.Null,
    'environmental' : IDL.Null,
    'sanction' : IDL.Null,
    'export' : IDL.Null,
    'monetary' : IDL.Null,
  });
  const PolicyEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'country' : IDL.Text,
    'policyType' : policyType,
    'marketImpact' : IDL.Text,
    'description' : IDL.Text,
    'severity' : IDL.Nat,
    'effectiveDate' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'organization' : IDL.Text,
  });
  const EventCorrelation = IDL.Record({
    'id' : IDL.Text,
    'targetEventId' : IDL.Text,
    'sourceEventId' : IDL.Text,
    'description' : IDL.Text,
    'strength' : IDL.Float64,
    'relationshipType' : IDL.Text,
  });
  const IndustryImpact = IDL.Record({
    'direction' : IDL.Variant({
      'up' : IDL.Null,
      'down' : IDL.Null,
      'neutral' : IDL.Null,
    }),
    'magnitude' : IDL.Float64,
    'industry' : IDL.Text,
    'reason' : IDL.Text,
  });
  const CommodityImpact = IDL.Record({
    'direction' : IDL.Variant({
      'up' : IDL.Null,
      'down' : IDL.Null,
      'neutral' : IDL.Null,
    }),
    'commodity' : IDL.Text,
    'magnitude' : IDL.Float64,
  });
  const MarketImpact = IDL.Record({
    'id' : IDL.Text,
    'eventId' : IDL.Text,
    'industryImpacts' : IDL.Vec(IndustryImpact),
    'createdAt' : Time,
    'eventTitle' : IDL.Text,
    'commodityImpacts' : IDL.Vec(CommodityImpact),
  });
  const SentimentRecord = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'country' : IDL.Text,
    'sentimentScore' : IDL.Float64,
    'source' : IDL.Text,
    'recordedAt' : Time,
    'narrativeTheme' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGlobalEvent' : IDL.Func([GlobalEvent], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createScenario' : IDL.Func([Scenario], [], []),
    'getAllCorrelationChains' : IDL.Func(
        [],
        [IDL.Vec(CorrelationChain)],
        ['query'],
      ),
    'getAllCountryRiskProfiles' : IDL.Func(
        [],
        [IDL.Vec(CountryRiskProfile)],
        ['query'],
      ),
    'getAllGlobalEvents' : IDL.Func(
        [
          IDL.Opt(
            IDL.Variant({
              'climate' : IDL.Null,
              'trade' : IDL.Null,
              'geopolitics' : IDL.Null,
              'military' : IDL.Null,
              'technology' : IDL.Null,
              'economic' : IDL.Null,
              'policy' : IDL.Null,
            })
          ),
        ],
        [IDL.Vec(GlobalEvent)],
        ['query'],
      ),
    'getAllInfluenceEdges' : IDL.Func([], [IDL.Vec(InfluenceEdge)], ['query']),
    'getAllPolicyEntries' : IDL.Func(
        [IDL.Opt(policyType)],
        [IDL.Vec(PolicyEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCorrelationsForEvent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EventCorrelation)],
        ['query'],
      ),
    'getCountryRiskByCode' : IDL.Func(
        [IDL.Text],
        [CountryRiskProfile],
        ['query'],
      ),
    'getDashboardSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEvents' : IDL.Nat,
            'highRiskCountries' : IDL.Vec(CountryRiskProfile),
            'activeScenarios' : IDL.Nat,
            'avgGlobalRisk' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getEventById' : IDL.Func([IDL.Text], [GlobalEvent], ['query']),
    'getMarketImpacts' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(MarketImpact)],
        ['query'],
      ),
    'getScenarioById' : IDL.Func([IDL.Text], [Scenario], ['query']),
    'getScenarios' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Scenario)],
        ['query'],
      ),
    'getSentimentRecords' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(SentimentRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCountryRisk' : IDL.Func([CountryRiskProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };