/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GlobalEvent {
    id: string;
    lat: number;
    lng: number;
    region: string;
    title: string;
    country: string;
    tags: Array<string>;
    description: string;
    timestamp: Time;
    category: Variant_climate_trade_geopolitics_military_technology_economic_policy;
    severity: bigint;
}
export type Time = bigint;
export interface ScenarioOutcome {
    probability: number;
    title: string;
    timelineWeeks: bigint;
    description: string;
    sectorsImpacted: Array<string>;
}
export interface PolicyEntry {
    id: string;
    title: string;
    country: string;
    policyType: policyType;
    marketImpact: string;
    description: string;
    severity: bigint;
    effectiveDate: Time;
}
export interface SentimentRecord {
    id: string;
    region: string;
    country: string;
    sentimentScore: number;
    source: string;
    recordedAt: Time;
    narrativeTheme: string;
}
export interface MarketImpact {
    id: string;
    eventId: string;
    industryImpacts: Array<IndustryImpact>;
    createdAt: Time;
    eventTitle: string;
    commodityImpacts: Array<CommodityImpact>;
}
export interface CountryRiskProfile {
    country: string;
    socialUnrest: number;
    politicalStability: number;
    lastUpdated: Time;
    militaryActivity: number;
    countryCode: string;
    sanctionsRisk: number;
    overallRisk: number;
    tradeDependency: number;
    economicScore: number;
}
export interface CommodityImpact {
    direction: Variant_up_down_neutral;
    commodity: string;
    magnitude: number;
}
export interface InfluenceEdge {
    id: string;
    relationship: string;
    description: string;
    strength: number;
    entityType: Variant_country_institution_corporation;
    targetEntity: string;
    sourceEntity: string;
}
export interface IndustryImpact {
    direction: Variant_up_down_neutral;
    magnitude: number;
    industry: string;
    reason: string;
}
export interface Scenario {
    id: string;
    title: string;
    createdAt: Time;
    outcomes: Array<ScenarioOutcome>;
    triggerEventId: string;
}
export interface CorrelationStep {
    eventId: string;
    description: string;
    stepLabel: string;
}
export interface EventCorrelation {
    id: string;
    targetEventId: string;
    sourceEventId: string;
    description: string;
    strength: number;
    relationshipType: string;
}
export interface UserProfile {
    name: string;
    role: string;
    organization: string;
}
export interface CorrelationChain {
    id: string;
    title: string;
    createdAt: Time;
    steps: Array<CorrelationStep>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_climate_trade_geopolitics_military_technology_economic_policy {
    climate = "climate",
    trade = "trade",
    geopolitics = "geopolitics",
    military = "military",
    technology = "technology",
    economic = "economic",
    policy = "policy"
}
export enum Variant_country_institution_corporation {
    country = "country",
    institution = "institution",
    corporation = "corporation"
}
export enum Variant_up_down_neutral {
    up = "up",
    down = "down",
    neutral = "neutral"
}
export enum policyType {
    regulation = "regulation",
    tariff = "tariff",
    environmental = "environmental",
    sanction = "sanction",
    export_ = "export",
    monetary = "monetary"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGlobalEvent(event: GlobalEvent): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createScenario(scenario: Scenario): Promise<void>;
    getAllCorrelationChains(): Promise<Array<CorrelationChain>>;
    getAllCountryRiskProfiles(): Promise<Array<CountryRiskProfile>>;
    getAllGlobalEvents(category: Variant_climate_trade_geopolitics_military_technology_economic_policy | null): Promise<Array<GlobalEvent>>;
    getAllInfluenceEdges(): Promise<Array<InfluenceEdge>>;
    getAllPolicyEntries(policyType: policyType | null): Promise<Array<PolicyEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCorrelationsForEvent(eventId: string): Promise<Array<EventCorrelation>>;
    getCountryRiskByCode(code: string): Promise<CountryRiskProfile>;
    getDashboardSummary(): Promise<{
        totalEvents: bigint;
        highRiskCountries: Array<CountryRiskProfile>;
        activeScenarios: bigint;
        avgGlobalRisk: number;
    }>;
    getEventById(id: string): Promise<GlobalEvent>;
    getMarketImpacts(eventId: string | null): Promise<Array<MarketImpact>>;
    getScenarioById(id: string): Promise<Scenario>;
    getScenarios(triggerEventId: string | null): Promise<Array<Scenario>>;
    getSentimentRecords(region: string | null): Promise<Array<SentimentRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCountryRisk(profile: CountryRiskProfile): Promise<void>;
}
import type { CommodityImpact as _CommodityImpact, GlobalEvent as _GlobalEvent, IndustryImpact as _IndustryImpact, InfluenceEdge as _InfluenceEdge, MarketImpact as _MarketImpact, PolicyEntry as _PolicyEntry, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, policyType as _policyType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGlobalEvent(arg0: GlobalEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGlobalEvent(to_candid_GlobalEvent_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGlobalEvent(to_candid_GlobalEvent_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createScenario(arg0: Scenario): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createScenario(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScenario(arg0);
            return result;
        }
    }
    async getAllCorrelationChains(): Promise<Array<CorrelationChain>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCorrelationChains();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCorrelationChains();
            return result;
        }
    }
    async getAllCountryRiskProfiles(): Promise<Array<CountryRiskProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCountryRiskProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCountryRiskProfiles();
            return result;
        }
    }
    async getAllGlobalEvents(arg0: Variant_climate_trade_geopolitics_military_technology_economic_policy | null): Promise<Array<GlobalEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGlobalEvents(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGlobalEvents(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInfluenceEdges(): Promise<Array<InfluenceEdge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInfluenceEdges();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInfluenceEdges();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPolicyEntries(arg0: policyType | null): Promise<Array<PolicyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPolicyEntries(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPolicyEntries(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCorrelationsForEvent(arg0: string): Promise<Array<EventCorrelation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCorrelationsForEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCorrelationsForEvent(arg0);
            return result;
        }
    }
    async getCountryRiskByCode(arg0: string): Promise<CountryRiskProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCountryRiskByCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCountryRiskByCode(arg0);
            return result;
        }
    }
    async getDashboardSummary(): Promise<{
        totalEvents: bigint;
        highRiskCountries: Array<CountryRiskProfile>;
        activeScenarios: bigint;
        avgGlobalRisk: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getEventById(arg0: string): Promise<GlobalEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventById(arg0);
                return from_candid_GlobalEvent_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventById(arg0);
            return from_candid_GlobalEvent_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketImpacts(arg0: string | null): Promise<Array<MarketImpact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketImpacts(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketImpacts(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScenarioById(arg0: string): Promise<Scenario> {
        if (this.processError) {
            try {
                const result = await this.actor.getScenarioById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScenarioById(arg0);
            return result;
        }
    }
    async getScenarios(arg0: string | null): Promise<Array<Scenario>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScenarios(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScenarios(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getSentimentRecords(arg0: string | null): Promise<Array<SentimentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentimentRecords(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentimentRecords(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCountryRisk(arg0: CountryRiskProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCountryRisk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCountryRisk(arg0);
            return result;
        }
    }
}
function from_candid_CommodityImpact_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommodityImpact): CommodityImpact {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_GlobalEvent_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GlobalEvent): GlobalEvent {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_IndustryImpact_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IndustryImpact): IndustryImpact {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_InfluenceEdge_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InfluenceEdge): InfluenceEdge {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_MarketImpact_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketImpact): MarketImpact {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PolicyEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PolicyEntry): PolicyEntry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_policyType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _policyType): policyType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    relationship: string;
    description: string;
    strength: number;
    entityType: {
        country: null;
    } | {
        institution: null;
    } | {
        corporation: null;
    };
    targetEntity: string;
    sourceEntity: string;
}): {
    id: string;
    relationship: string;
    description: string;
    strength: number;
    entityType: Variant_country_institution_corporation;
    targetEntity: string;
    sourceEntity: string;
} {
    return {
        id: value.id,
        relationship: value.relationship,
        description: value.description,
        strength: value.strength,
        entityType: from_candid_variant_n14(_uploadFile, _downloadFile, value.entityType),
        targetEntity: value.targetEntity,
        sourceEntity: value.sourceEntity
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    country: string;
    policyType: _policyType;
    marketImpact: string;
    description: string;
    severity: bigint;
    effectiveDate: _Time;
}): {
    id: string;
    title: string;
    country: string;
    policyType: policyType;
    marketImpact: string;
    description: string;
    severity: bigint;
    effectiveDate: Time;
} {
    return {
        id: value.id,
        title: value.title,
        country: value.country,
        policyType: from_candid_policyType_n21(_uploadFile, _downloadFile, value.policyType),
        marketImpact: value.marketImpact,
        description: value.description,
        severity: value.severity,
        effectiveDate: value.effectiveDate
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    eventId: string;
    industryImpacts: Array<_IndustryImpact>;
    createdAt: _Time;
    eventTitle: string;
    commodityImpacts: Array<_CommodityImpact>;
}): {
    id: string;
    eventId: string;
    industryImpacts: Array<IndustryImpact>;
    createdAt: Time;
    eventTitle: string;
    commodityImpacts: Array<CommodityImpact>;
} {
    return {
        id: value.id,
        eventId: value.eventId,
        industryImpacts: from_candid_vec_n30(_uploadFile, _downloadFile, value.industryImpacts),
        createdAt: value.createdAt,
        eventTitle: value.eventTitle,
        commodityImpacts: from_candid_vec_n34(_uploadFile, _downloadFile, value.commodityImpacts)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: {
        up: null;
    } | {
        down: null;
    } | {
        neutral: null;
    };
    magnitude: number;
    industry: string;
    reason: string;
}): {
    direction: Variant_up_down_neutral;
    magnitude: number;
    industry: string;
    reason: string;
} {
    return {
        direction: from_candid_variant_n33(_uploadFile, _downloadFile, value.direction),
        magnitude: value.magnitude,
        industry: value.industry,
        reason: value.reason
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: {
        up: null;
    } | {
        down: null;
    } | {
        neutral: null;
    };
    commodity: string;
    magnitude: number;
}): {
    direction: Variant_up_down_neutral;
    commodity: string;
    magnitude: number;
} {
    return {
        direction: from_candid_variant_n33(_uploadFile, _downloadFile, value.direction),
        commodity: value.commodity,
        magnitude: value.magnitude
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lat: number;
    lng: number;
    region: string;
    title: string;
    country: string;
    tags: Array<string>;
    description: string;
    timestamp: _Time;
    category: {
        climate: null;
    } | {
        trade: null;
    } | {
        geopolitics: null;
    } | {
        military: null;
    } | {
        technology: null;
    } | {
        economic: null;
    } | {
        policy: null;
    };
    severity: bigint;
}): {
    id: string;
    lat: number;
    lng: number;
    region: string;
    title: string;
    country: string;
    tags: Array<string>;
    description: string;
    timestamp: Time;
    category: Variant_climate_trade_geopolitics_military_technology_economic_policy;
    severity: bigint;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        region: value.region,
        title: value.title,
        country: value.country,
        tags: value.tags,
        description: value.description,
        timestamp: value.timestamp,
        category: from_candid_variant_n10(_uploadFile, _downloadFile, value.category),
        severity: value.severity
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    climate: null;
} | {
    trade: null;
} | {
    geopolitics: null;
} | {
    military: null;
} | {
    technology: null;
} | {
    economic: null;
} | {
    policy: null;
}): Variant_climate_trade_geopolitics_military_technology_economic_policy {
    return "climate" in value ? Variant_climate_trade_geopolitics_military_technology_economic_policy.climate : "trade" in value ? Variant_climate_trade_geopolitics_military_technology_economic_policy.trade : "geopolitics" in value ? Variant_climate_trade_geopolitics_military_technology_economic_policy.geopolitics : "military" in value ? Variant_climate_trade_geopolitics_military_technology_economic_policy.military : "technology" in value ? Variant_climate_trade_geopolitics_military_technology_economic_policy.technology : "economic" in value ? Variant_climate_trade_geopolitics_military_technology_economic_policy.economic : "policy" in value ? Variant_climate_trade_geopolitics_military_technology_economic_policy.policy : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: null;
} | {
    institution: null;
} | {
    corporation: null;
}): Variant_country_institution_corporation {
    return "country" in value ? Variant_country_institution_corporation.country : "institution" in value ? Variant_country_institution_corporation.institution : "corporation" in value ? Variant_country_institution_corporation.corporation : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    regulation: null;
} | {
    tariff: null;
} | {
    environmental: null;
} | {
    sanction: null;
} | {
    export: null;
} | {
    monetary: null;
}): policyType {
    return "regulation" in value ? policyType.regulation : "tariff" in value ? policyType.tariff : "environmental" in value ? policyType.environmental : "sanction" in value ? policyType.sanction : "export" in value ? policyType.export : "monetary" in value ? policyType.monetary : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    up: null;
} | {
    down: null;
} | {
    neutral: null;
}): Variant_up_down_neutral {
    return "up" in value ? Variant_up_down_neutral.up : "down" in value ? Variant_up_down_neutral.down : "neutral" in value ? Variant_up_down_neutral.neutral : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InfluenceEdge>): Array<InfluenceEdge> {
    return value.map((x)=>from_candid_InfluenceEdge_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PolicyEntry>): Array<PolicyEntry> {
    return value.map((x)=>from_candid_PolicyEntry_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketImpact>): Array<MarketImpact> {
    return value.map((x)=>from_candid_MarketImpact_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IndustryImpact>): Array<IndustryImpact> {
    return value.map((x)=>from_candid_IndustryImpact_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommodityImpact>): Array<CommodityImpact> {
    return value.map((x)=>from_candid_CommodityImpact_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GlobalEvent>): Array<GlobalEvent> {
    return value.map((x)=>from_candid_GlobalEvent_n8(_uploadFile, _downloadFile, x));
}
function to_candid_GlobalEvent_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GlobalEvent): _GlobalEvent {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: policyType | null): [] | [_policyType] {
    return value === null ? candid_none() : candid_some(to_candid_policyType_n16(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_climate_trade_geopolitics_military_technology_economic_policy | null): [] | [{
        climate: null;
    } | {
        trade: null;
    } | {
        geopolitics: null;
    } | {
        military: null;
    } | {
        technology: null;
    } | {
        economic: null;
    } | {
        policy: null;
    }] {
    return value === null ? candid_none() : candid_some(to_candid_variant_n3(_uploadFile, _downloadFile, value));
}
function to_candid_policyType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: policyType): _policyType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lat: number;
    lng: number;
    region: string;
    title: string;
    country: string;
    tags: Array<string>;
    description: string;
    timestamp: Time;
    category: Variant_climate_trade_geopolitics_military_technology_economic_policy;
    severity: bigint;
}): {
    id: string;
    lat: number;
    lng: number;
    region: string;
    title: string;
    country: string;
    tags: Array<string>;
    description: string;
    timestamp: _Time;
    category: {
        climate: null;
    } | {
        trade: null;
    } | {
        geopolitics: null;
    } | {
        military: null;
    } | {
        technology: null;
    } | {
        economic: null;
    } | {
        policy: null;
    };
    severity: bigint;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        region: value.region,
        title: value.title,
        country: value.country,
        tags: value.tags,
        description: value.description,
        timestamp: value.timestamp,
        category: to_candid_variant_n3(_uploadFile, _downloadFile, value.category),
        severity: value.severity
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: policyType): {
    regulation: null;
} | {
    tariff: null;
} | {
    environmental: null;
} | {
    sanction: null;
} | {
    export: null;
} | {
    monetary: null;
} {
    return value == policyType.regulation ? {
        regulation: null
    } : value == policyType.tariff ? {
        tariff: null
    } : value == policyType.environmental ? {
        environmental: null
    } : value == policyType.sanction ? {
        sanction: null
    } : value == policyType.export ? {
        export_: null
    } : value == policyType.monetary ? {
        monetary: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_climate_trade_geopolitics_military_technology_economic_policy): {
    climate: null;
} | {
    trade: null;
} | {
    geopolitics: null;
} | {
    military: null;
} | {
    technology: null;
} | {
    economic: null;
} | {
    policy: null;
} {
    return value == Variant_climate_trade_geopolitics_military_technology_economic_policy.climate ? {
        climate: null
    } : value == Variant_climate_trade_geopolitics_military_technology_economic_policy.trade ? {
        trade: null
    } : value == Variant_climate_trade_geopolitics_military_technology_economic_policy.geopolitics ? {
        geopolitics: null
    } : value == Variant_climate_trade_geopolitics_military_technology_economic_policy.military ? {
        military: null
    } : value == Variant_climate_trade_geopolitics_military_technology_economic_policy.technology ? {
        technology: null
    } : value == Variant_climate_trade_geopolitics_military_technology_economic_policy.economic ? {
        economic: null
    } : value == Variant_climate_trade_geopolitics_military_technology_economic_policy.policy ? {
        policy: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
